### ISSUE TITLE
nlp response groovy script error

### ISSUE THREAD

**Issue by farnooshsadeghian** [CogStack/CogStack-NiFi#12]
Using the script "parse-anns-from-nlp-response-bulk.groovy" in the nifi annotation workflow gives an error as it cannot validate ann_id using "assert ann_id". I had to convert the ann_id type to string to make it work:

    def ann_id = outAnn[annotation_id_field as String]
    assert ann_id.**toString()**

**Comment by vladd-bit** [comment]
I've just tested again but I do not encounter this issue, have you also updated MedCAT service to the latest version ?

**Comment by farnooshsadeghian** [comment]
That's interesting Vlad. yes, I use the latest version of Medcatservice (Cogstack-Nifi in general) and this error happens in es-to-es workflow.

**Comment by vladd-bit** [comment]
Well, added the fix anyhow, should work for all cases.
