### ISSUE TITLE
Any plans to move from OpenDistro to OpenSearch?

### ISSUE THREAD

**Issue by vmenger** [CogStack/CogStack-NiFi#13]
It seems the work on OpenDistro has now quite definitively moved into OpenSearch, see e.g: https://opendistro.github.io/for-elasticsearch/blog/2021/06/forward-to-opensearch/

Do you happen to have any plans moving to OpenSearch? As far as I can tell right now, this should not result in very fundamental problems. Kibana is renamed OpenSearch Dashboards, and still comes in a separate docker. 

In the short term, the problem for me is that OpenDistro does not support docker for Apple M1 chips, so I cannot work with it locally anymore. I might try to make the change myself, but just wondering if you had any thoughts on the issue. 

Thanks!
-Vincent

**Comment by vladd-bit** [comment]
Hello Vincent,

We have opensearch on the dev branch along with other new changes we plan to make to NiFi, you can find the sample deployment file at https://github.com/CogStack/CogStack-NiFi/blob/devel/deploy/services.yml and a working config at https://github.com/CogStack/CogStack-NiFi/blob/devel/services/elasticsearch/config/elasticsearch_opendistro.yml . We plan to get this rolled out over the next few weeks on the master branch, feel free to use these as a starting point though. 

Regarding Apple M1, apologies for this, we don't currently have any way of testing on the new chips, if we did we probably would have known of this issue.

**Comment by vmenger** [comment]
Great, that clears it up, I'll use your dev branch to start the move to opensearch in our UMCU fork, then later we'll start tracking master again. No worries about the Apple M1 chips, it's just not supported by the opendistro dockers, so not much anyone could have done there.
