### ISSUE TITLE
Upgrade opendistro/opensearch for log4j vulnerability

### ISSUE THREAD

**Issue by vmenger** [CogStack/CogStack-NiFi#15]
You're probably well aware, but you it's recommended to upgrade to OpenDistro >= 1.13.3 or OpenSearch >=1.2.1 asap to mitigate the log4j vulnerability (see: the internet).

https://opendistro.github.io/for-elasticsearch/blog/2021/12/update-to-1-13-3/
https://opensearch.org/blog/releases/2021/12/update-to-1-2-1/

**Comment by vladd-bit** [comment]
Yep. Updated on the master/dev branches.
